### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by asegun-cod** [CDU-data-science-team/zero-shot#4]
I'll appreciate any suggestion on how to get the training pipeline (hf_T_training_Bert.ipynb) to work, the actual training and evealuation code wont work.  Can't figure out the error but think this has to do with the preprocessing of the data.

**Comment by ChrisBeeley** [comment]
When there are multiple branches it can be useful to link to the file in question https://github.com/CDU-data-science-team/zero-shot/blob/feature-Huggingface_transformer/hf_T_training_Bert.ipynb

**Comment by andreassot10** [comment]
@asegun-cod, can you provide me with a link to the page where you copied the copy for https://github.com/CDU-data-science-team/zero-shot/blob/feature-Huggingface_transformer/hf_T_training_Bert.ipynb from?

**Comment by asegun-cod** [comment]
here are some of the resources I explored 
https://huggingface.co/transformers/training.html 
https://huggingface.co/transformers/custom_datasets.html#datasetslib
https://colab.research.google.com/drive/1-JIJlao4dI-Ilww_NnTc0rxtp-ymgDgM?usp=sharing#scrollTo=hJiTRNTE6wAI

**Comment by asegun-cod** [comment]
@andreassot10 this are the basic approach which include just using the model as a black box similar to the approach [Patient_Feedback_with_Hugging_Transformer](https://github.com/CDU-data-science-team/zero-shot/blob/feature-Huggingface_transformer/Patient_Feedback_with_Hugging_Transformer.ipynb) pipeline  uses. 
we need to dive into fine-tunning the models which is what I am trying to achieve with [hf_T_training_Bert](https://github.com/CDU-data-science-team/zero-shot/blob/feature-Huggingface_transformer/hf_T_training_Bert.ipynb) pipeline.

**Comment by andreassot10** [comment]
OK, I'll take a look a gain once I've progressed the HF course further, so that I understand what I'm doing.

But there must be a way to fine-tune `pipeline("zero-shot-classification")`, surely?

Also, for a starter it may be best to focus on finding how to make `pipeline("zero-shot-classification")` run for the whole dataset without running into memory issues. I think that scaling is much more important than fine-tuning at this point. If we can't scale, there's no point. @ChrisBeeley, what do you think the priority should be?

**Comment by ChrisBeeley** [comment]
Well, how much RAM do you have @asegun-cod ? It probably needs to fit into about 10GB realistically but do you have that much spare on your machine?

I'm almost more interested in knowing how much RAM it needs rather than necessarily making it fit. If it needs 32GB but it's awesome, we can probably get 32 GB from somewhere

**Comment by asegun-cod** [comment]
@andreassot10 i agree with the need to understand the fundamentals of huggingface.  Running pipeline `<"zero-shot-classification">` uses the default model which is 'bart-large-mnli' i think.[Patient_Feedback_with_Hugging_Transformer](https://github.com/CDU-data-science-team/zero-shot/blob/feature-Huggingface_transformer/Patient_Feedback_with_Hugging_Transformer.ipynb) kind of follow the same approach but the reason why the current [Patient_Feedback_with_Hugging_Transformer](https://github.com/CDU-data-science-team/zero-shot/blob/feature-Huggingface_transformer/Patient_Feedback_with_Hugging_Transformer.ipynb) pipeline took loads of time is that I am trying five different models to compare their efficiency. the best performing model for example uses only 09min 38sec to predict on 9k+ rows in the dataset used.
Just mentioning this hoping it might help our understanding of what is obtainable from the package.

**Comment by asegun-cod** [comment]
> Well, how much RAM do you have @asegun-cod ? It probably needs to fit into about 10GB realistically but do you have that much spare on your machine?
> 
> I'm almost more interested in knowing how much RAM it needs rather than necessarily making it fit. If it needs 32GB but it's awesome, we can probably get 32 GB from somewhere

@ChrisBeeley I don't really know much about the resources need and I will appreciate it if you can lecture me on how to check for this.  I don't run any of the code on my, machine again, I use colab strictly with GPU. 
but for now, I think you might be better at answering this question for me. please can you help test [Patient_Feedback_with_Hugging_Transformer](https://github.com/CDU-data-science-team/zero-shot/blob/feature-Huggingface_transformer/Patient_Feedback_with_Hugging_Transformer.ipynb) pipeline by uncommenting the `#for testing the pipeline` section under the `#List of pretrained Zeroshot models to test` and commenting out the current `models` list.

**Comment by asegun-cod** [comment]
As regards scaling, what timeframe are we looking at? and will GPU be available?

**Comment by ChrisBeeley** [comment]
A profiler would be great, have a look at this thread https://stackoverflow.com/questions/110259/which-python-memory-profiler-is-recommended

No GPU, I can guarantee that :laughing: 

Don't worry about scaling and timeframes, there aren't clear answers anyway, just do what you can for now

**Comment by ChrisBeeley** [comment]
I forgot to say thanks! You're doing a lot of useful stuff :+1:
