### ISSUE TITLE
Jupyter notebooks versus Python scripts

### ISSUE THREAD

**Issue by andreassot10** [CDU-data-science-team/zero-shot#5]
I don't know if @ChrisBeeley and @asegun-cod have a strong opinion on this, but I personally find the conversion from `ipynb` to `py` and the other way around pretty annoying. I've been converting @asegun-cod's notebooks to `py` in order to run them on my machine and make any changes. On the other hand, I believe that @asegun-cod then converts them back to `ipynb` because he prefers this format.

Since I'm leaving, I'll leave it up to @ChrisBeeley and @asegun-cod to decide how to go about it (e.g. use one format or stick to conversions) from now on.

**Comment by ChrisBeeley** [comment]
I just open them in VS Code, that's pretty straightforward. Not sure about modifying and making PRs though, haven't done that myself

**Comment by asegun-cod** [comment]
I don't mind using any format and I think since @ChrisBeeley uses VS code I'll advise we just stick to `py` file. Though I work with `ipynb` (and might always do going forward), however I can always convert my code to `py` to maintain same format. I do work in VS code too.
